bump postgrest & build for arm

diff --git a/src/pgrest/install-pgrest b/src/pgrest/install-pgrest
--- a/src/pgrest/install-pgrest
+++ b/src/pgrest/install-pgrest
@@ -1,56 +1,56 @@
 #!/bin/bash
 cd "$(dirname "$0")"
 
-ver=$1
+#ver=$1
 
-url=https://github.com/PostgREST/postgrest/releases/download/v$ver
-file=postgrest-v$ver
+#url=https://github.com/PostgREST/postgrest/releases/download/v$ver
+#file=postgrest-v$ver
 
-if [ "$ver" == "" ]; then
-  echo "ERROR: missing version # on the command line"
-  exit 1
-fi
+#if [ "$ver" == "" ]; then
+#  echo "ERROR: missing version # on the command line"
+#  exit 1
+#fi
 
-echo " "  
-echo "######## Installing pgREST v$ver ########"
+#echo " "  
+#echo "######## Installing pgREST v$ver ########"
 
-os=`uname -s`
-if [ "$os" == "Darwin" ]; then
-  flavor=macos-x64
-elif [ "$os" == "Linux" ]; then
-  yum --version > /dev/null 2>&1
-  rc=$?
-  arch=`arch`
-  if [ "$rc" == "0" ] && [ "$arch" == "x86_64" ]; then
-    flavor=linux-static-x64
-  elif [ "$arch" == "aarch64" ]; then
-    flavor=ubuntu-aarch64
-  else
-    echo "$arch is not presently support"
-  fi
-fi
+#os=`uname -s`
+#if [ "$os" == "Darwin" ]; then
+#  flavor=macos-x64
+#elif [ "$os" == "Linux" ]; then
+#  yum --version > /dev/null 2>&1
+#  rc=$?
+#  arch=`arch`
+#  if [ "$rc" == "0" ] && [ "$arch" == "x86_64" ]; then
+#    flavor=linux-static-x64
+#  elif [ "$arch" == "aarch64" ]; then
+#    flavor=ubuntu-aarch64
+#  else
+#    echo "$arch is not presently support"
+#  fi
+#fi
 
-full_file=$file-$flavor.tar.xz
+#full_file=$file-$flavor.tar.xz
 
-rm -f $full_file*
-rm -f postgrest
+#rm -f $full_file*
+#rm -f postgrest
 
-echo " downloading $full_file from $url .."
-wget -q $url/$full_file
-rc=$?
-if [ "$rc" != "0" ]; then
-  echo "ERROR: $ver not found or cannot download"
-  exit 1
-fi
+#echo " downloading $full_file from $url .."
+#wget -q $url/$full_file
+#rc=$?
+#if [ "$rc" != "0" ]; then
+#  echo "ERROR: $ver not found or cannot download"
+#  exit 1
+#fi
 
-echo " extracting $full_file ... "
-tar -xf $full_file
-rc=$?
-if [ "$rc" != "0" ]; then
-  exit 1
-else
-  rm $full_file*
-fi
+#echo " extracting $full_file ... "
+#tar -xf $full_file
+#rc=$?
+#if [ "$rc" != "0" ]; then
+#  exit 1
+#else
+#  rm $full_file*
+#fi
 
 port=5432
 echo " creating default config file pgrest.conf with following lines:"
